version : "3.8"
services : 
  java-maven-app :
    image: ${IMAGE}
    ports :
      - 8080:8080
  postgress :
    image : postgres
    ports :
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: PASS
